---
- name: UInstall nginx on CentOS
  # CentOS는 Node01, Node02의 Group Name
  hosts: CentOS
  gather_facts: no
  # Root권한을 획득하는 명령어
  become: yes
  tasks:
    - name: Uinstall epel-release
      yum: name=epel-release state=absent
    - name: install nginx web server
      yum: name=nginx state=absent
